// Assembly file generated by my awesome VM compiler
// Input filename: StackTest.vm
// 'push constant 17' (line 0)
@17
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 17' (line 1)
@17
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'eq' (line 2)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@COMP.0.TRUE
D;JEQ
@COMP.0.FALSE
0;JMP
(COMP.0.TRUE)
@SP
A=M
M=-1
@SP
M=M+1
@COMP.0.END
0;JMP
(COMP.0.FALSE)
@SP
A=M
M=0
@SP
M=M+1
(COMP.0.END)
// 'push constant 892' (line 3)
@892
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 891' (line 4)
@891
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'lt' (line 5)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@COMP.1.TRUE
D;JLT
@COMP.1.FALSE
0;JMP
(COMP.1.TRUE)
@SP
A=M
M=-1
@SP
M=M+1
@COMP.1.END
0;JMP
(COMP.1.FALSE)
@SP
A=M
M=0
@SP
M=M+1
(COMP.1.END)
// 'push constant 32767' (line 6)
@32767
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 32766' (line 7)
@32766
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'gt' (line 8)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@COMP.2.TRUE
D;JGT
@COMP.2.FALSE
0;JMP
(COMP.2.TRUE)
@SP
A=M
M=-1
@SP
M=M+1
@COMP.2.END
0;JMP
(COMP.2.FALSE)
@SP
A=M
M=0
@SP
M=M+1
(COMP.2.END)
// 'push constant 56' (line 9)
@56
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 31' (line 10)
@31
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 53' (line 11)
@53
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'add' (line 12)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M+D
@SP
M=M+1
// 'push constant 112' (line 13)
@112
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'sub' (line 14)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M-D
@SP
M=M+1
// 'neg' (line 15)
@SP
AM=M-1
M=-M
@SP
M=M+1
// 'and' (line 16)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M&D
@SP
M=M+1
// 'push constant 82' (line 17)
@82
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'or' (line 18)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M|D
@SP
M=M+1
(END)
@END
0;JMP