// Assembly file generated by my awesome VM compiler
// Input filename: StackTest.vm
// 'push constant 17' (line 0)
@17
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 17' (line 1)
@17
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'eq' (line 2)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@TRUE.0
D;JEQ
@FALSE.0
0;JMP
(TRUE.0)
@SP
A=M
M=1
@SP
M=M+1
@END.0
0;JMP
(FALSE.0)
@SP
A=M
M=0
@SP
M=M+1
(END.0)
// 'push constant 892' (line 3)
@892
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 891' (line 4)
@891
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'lt' (line 5)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@TRUE.1
D;JLT
@FALSE.1
0;JMP
(TRUE.1)
@SP
A=M
M=1
@SP
M=M+1
@END.1
0;JMP
(FALSE.1)
@SP
A=M
M=0
@SP
M=M+1
(END.1)
// 'push constant 32767' (line 6)
@32767
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 32766' (line 7)
@32766
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'gt' (line 8)
@SP
AM=M-1
D=M
@SP
AM=M-1
D=M-D
@TRUE.2
D;JGT
@FALSE.2
0;JMP
(TRUE.2)
@SP
A=M
M=1
@SP
M=M+1
@END.2
0;JMP
(FALSE.2)
@SP
A=M
M=0
@SP
M=M+1
(END.2)
// 'push constant 56' (line 9)
@56
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 31' (line 10)
@31
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'push constant 53' (line 11)
@53
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'add' (line 12)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M+D
@SP
M=M+1
// 'push constant 112' (line 13)
@112
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'sub' (line 14)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M-D
@SP
M=M+1
// 'neg' (line 15)
@SP
AM=M-1
M=-M
@SP
M=M+1
// 'and' (line 16)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M&D
@SP
M=M+1
// 'push constant 82' (line 17)
@82
D=A
@SP
A=M
M=D
@SP
M=M+1
// 'or' (line 18)
@SP
AM=M-1
D=M
@SP
AM=M-1
M=M|D
@SP
M=M+1
(END)
@END
0;JMP